### PR TITLE
Thread Reaping

### PR DESCRIPTION
**Pull request by DerekCresswell**

### CODE REVIEW

**Comment by DerekCresswell** [comment]
This is failing from underflow on the interrupt lock.

**Comment by DerekCresswell** [comment]
After getting the interrupts into a good state, I find this getting a triple fault when returning from the context switch into the idle function.

I thought maybe it could be to do with returning the Option from ThreadFunctions, as Rust reports this is not FFI-safe. However this did not alleviate the issue.

This error also occurred in the interrupts before #18 .  The issue was with the stack pointer being decremented / incremented by non-aligned amounts.

**Comment by DerekCresswell** [comment]
Added here (though not dependent on the other code in the PR) is updated documentation for the threading Readme. I hope it, combined with any code comments, should aide in getting developers up to speed on KidneyOS's threading system.

**Comment by ff-zhang** [comment]
Changes incorporated into main already. Opened a new issue for current thread cleanup bugs.

**Pull request closed without merging**
